travis:
  secure:
    BINSTAR_TOKEN: U7J2CXlq5RtEkOQKjc8VtcfU/rPAjWpvpGkwBlBWeDVjvCAHCCbr3NVjM1wxrBR8WSKDhZtn2acJn2njNrp8fMS4Y55018qGVkd1hSlGuVIBPWimJZsk/l/8A5d590FRTssiOj59yg7wA71R8v4b8hNMwjD5npQpjGzbWFkB2Kt6enlAHoiDpMUuyS5BPfFwvkgMwfEjkIFjOJCBPOsOD5kRNTZg1BYxmCVlN0JL9xy26lDKmodZibLjMTy1X7h/wUf1Wv9AteW/e9+qBdY4qz5pi15fSaHmIbgzpuTVeWENrYvoy3Qe4CtHse859J3XIhYkDpiPBiWl7ixqZnjd+/Cjh67844tmJsKMrjKUTPo9QtAFXal7h/bGUdI1ycGBQheODjxwCDA3/ISSwrqD5g2wu11iTjnWLcVwL5f+9uLaNMd9xZ/lXWkSwa08kdpLr4MBzud/H+uIPl6iladtiTyCvWyR81On2a6EcYrIlsi0utBf8C7H10KNvBmuGr0FEON2MVTOUzPftArlaImGvCkCMvbc7AJFr5a/XDV2e2ERsNXLruZZO/4ZB9PVftROKfZwEbZMI8xUjCbpib2jFJyKw8WoSv0O7ogEXum9q88sMi80cnhw+XClSVFubmMxmCFVmnmPyfA/TmQzVUJDZqZd5RuPvqE8LusvLpiQUCQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
