travis:
  secure:
    BINSTAR_TOKEN: sP7WN+ygma7R+/KzB3Mc6LjgpOn1TIFVYEyIfr0m6Wj3+Hj/ICm87jtkGcax6V9ZpffwfF3jh11uR4jh6pQiIhX+Qem3ZmhddMZgQQpZu/keieh3k4kJ3G7UJUayy9o+RsYeQbmD1TN1qkXxJTs12EpXGITogtBmPESGYkszYLDzzFYEMThV+X1PGSQ4H2rmdxxDsx29x6w/jXmesJrZ58CUbeVBoCQAIRpnMAcLgiDJY2pXb672fqLM2n9kSO62Zo9p+O8JGLijZXzwXPb7S6vtSgzOl7Rl89GZzSFkoY5qiHJa0jigVbogefpqv9P9yKNJJf1E16ReMaAyH0q/lrBSg64dlK6wNOCiyL8UbjAwGxjR58UInI9k/M7vk1ZdDusnM1wlw7b6vsMAqysajU3dupGc5ChuhrXTNLbXKFJaKH9cfpAuBa/ynOFi55zGm+DkdDDaUd5Xxn8gx6Rbo+evpPo/T2sFNl1D7zIWXHD4Qmth3jW782PVmrtet/ZZQEpCE5ka9IA62BQ8adhEmj0MINjj3Cz0J6C9WsIoqnxvWK89X5kBM++4iHy25k8qqXZOkaeeLsduZwMKizFLovPBuapIlrTth1d27WQZGfayLMjYla8MHVpUXhyWEypzzKjhnoIXJ05rCaurUE0FDqD9CM8EaiPEaso+p5pYigQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
